model_path: models/table_infer_en.onnx

use_cuda: true
CUDAExecutionProvider:
    device_id: 0
    arena_extend_strategy: kNextPowerOfTwo
    cudnn_conv_algo_search: EXHAUSTIVE
    do_copy_in_default_stream: true

table_algorithm: TableAttn
table_max_len: 488
table_char_dict_path: table_structure_dict.txt
merge_no_span_structure: true